-- AJURA: lista oficial de serviços; execute uma vez no SQL Editor.
-- Mantém registros antigos para revisão e impede novos serviços fora da lista.
create table if not exists public.service_taxonomy (
  category text not null,
  subcategory text not null,
  primary key (category, subcategory)
);

insert into public.service_taxonomy (category, subcategory) values
  ('Elétrica', 'Tomadas e interruptores'),
  ('Elétrica', 'Iluminação'),
  ('Elétrica', 'Ventiladores'),
  ('Elétrica', 'Diagnóstico elétrico'),
  ('Elétrica', 'Quadros'),
  ('Elétrica', 'Chuveiros'),
  ('Elétrica', 'Fiação e circuitos'),
  ('Elétrica', 'Padrão de entrada'),
  ('Elétrica', 'Aterramento e proteção'),
  ('Elétrica', 'Geradores e nobreaks'),
  ('Hidráulica', 'Torneiras'),
  ('Hidráulica', 'Vazamentos'),
  ('Hidráulica', 'Vasos e descargas'),
  ('Hidráulica', 'Caixas-d’água'),
  ('Hidráulica', 'Sifões e ralos'),
  ('Hidráulica', 'Bombas d’água'),
  ('Hidráulica', 'Tubulações'),
  ('Hidráulica', 'Desentupimento'),
  ('Climatização', 'Limpeza de split'),
  ('Climatização', 'Instalação'),
  ('Climatização', 'Diagnóstico de ar-condicionado'),
  ('Climatização', 'Manutenção preventiva'),
  ('Climatização', 'Reparo de ar-condicionado'),
  ('Climatização', 'Climatização comercial'),
  ('Gás residencial', 'Inspeção de instalação'),
  ('Gás residencial', 'Detecção de vazamento'),
  ('Gás residencial', 'Instalação de ponto de gás'),
  ('Gás residencial', 'Conversão de aparelho'),
  ('Montagem', 'Móveis'),
  ('Montagem', 'Prateleiras e suportes'),
  ('Montagem', 'Cortinas e varais'),
  ('Montagem', 'Suportes de TV'),
  ('Montagem', 'Equipamentos de academia'),
  ('Pintura e reparos', 'Pintura'),
  ('Pintura e reparos', 'Portas e ferragens'),
  ('Pintura e reparos', 'Vedação'),
  ('Pintura e reparos', 'Textura e acabamento'),
  ('Pintura e reparos', 'Papel de parede'),
  ('Pintura e reparos', 'Pequenos reparos'),
  ('Reforma e construção', 'Alvenaria'),
  ('Reforma e construção', 'Pisos e revestimentos'),
  ('Reforma e construção', 'Gesso e drywall'),
  ('Reforma e construção', 'Forro'),
  ('Reforma e construção', 'Impermeabilização'),
  ('Reforma e construção', 'Demolição controlada'),
  ('Reforma e construção', 'Reforma de cômodo'),
  ('Marcenaria', 'Móveis sob medida'),
  ('Marcenaria', 'Reparo de móveis'),
  ('Marcenaria', 'Portas de madeira'),
  ('Marcenaria', 'Ajuste de gavetas e dobradiças'),
  ('Serralheria', 'Portões e grades'),
  ('Serralheria', 'Soldagem'),
  ('Serralheria', 'Estruturas metálicas'),
  ('Serralheria', 'Corrimãos'),
  ('Vidraçaria', 'Vidros e espelhos'),
  ('Vidraçaria', 'Box de banheiro'),
  ('Vidraçaria', 'Janelas de vidro'),
  ('Vidraçaria', 'Tampos de mesa'),
  ('Telhados e calhas', 'Reparo de telhado'),
  ('Telhados e calhas', 'Limpeza de calhas'),
  ('Telhados e calhas', 'Instalação de calhas'),
  ('Telhados e calhas', 'Detecção de infiltração'),
  ('Chaveiro e acesso', 'Abertura de porta'),
  ('Chaveiro e acesso', 'Troca de fechadura'),
  ('Chaveiro e acesso', 'Cópia de chaves'),
  ('Chaveiro e acesso', 'Fechadura digital'),
  ('Chaveiro e acesso', 'Controle de portão'),
  ('Dedetização', 'Insetos rasteiros'),
  ('Dedetização', 'Cupins'),
  ('Dedetização', 'Roedores'),
  ('Dedetização', 'Limpeza de caixa-d’água'),
  ('Dedetização', 'Controle de pragas'),
  ('Jardim e piscina', 'Jardinagem'),
  ('Jardim e piscina', 'Poda'),
  ('Jardim e piscina', 'Paisagismo'),
  ('Jardim e piscina', 'Limpeza de piscina'),
  ('Jardim e piscina', 'Manutenção de piscina'),
  ('Jardim e piscina', 'Irrigação'),
  ('Energia solar', 'Projeto fotovoltaico'),
  ('Energia solar', 'Instalação solar'),
  ('Energia solar', 'Limpeza de módulos'),
  ('Energia solar', 'Diagnóstico e manutenção'),
  ('Energia solar', 'Homologação'),
  ('Internet e redes', 'Roteadores e Wi-Fi'),
  ('Internet e redes', 'Rede mesh'),
  ('Internet e redes', 'Cabeamento e pontos de rede'),
  ('Internet e redes', 'Fibra óptica interna'),
  ('Internet e redes', 'Diagnóstico de conexão'),
  ('Celulares e eletrônicos', 'Celulares e tablets'),
  ('Celulares e eletrônicos', 'Computadores e notebooks'),
  ('Celulares e eletrônicos', 'TVs e monitores'),
  ('Celulares e eletrônicos', 'Videogames e controles'),
  ('Celulares e eletrônicos', 'Áudio e eletrônicos'),
  ('Celulares e eletrônicos', 'Pequenos eletrodomésticos'),
  ('Celulares e eletrônicos', 'Impressoras'),
  ('Segurança eletrônica', 'Câmeras e CFTV'),
  ('Segurança eletrônica', 'Alarmes'),
  ('Segurança eletrônica', 'Interfone'),
  ('Segurança eletrônica', 'Cerca elétrica'),
  ('Segurança eletrônica', 'Controle de acesso'),
  ('Casa inteligente', 'Automação residencial'),
  ('Casa inteligente', 'Assistentes de voz'),
  ('Casa inteligente', 'Iluminação inteligente'),
  ('Casa inteligente', 'Sensores e fechaduras'),
  ('Serviços digitais', 'Criação de site'),
  ('Serviços digitais', 'Suporte remoto'),
  ('Serviços digitais', 'Configuração de e-mail'),
  ('Serviços digitais', 'Recuperação de dados'),
  ('Serviços digitais', 'Design gráfico'),
  ('Serviços digitais', 'Edição de vídeo'),
  ('Limpeza', 'Residencial'),
  ('Limpeza', 'Comercial'),
  ('Limpeza', 'Pós-obra'),
  ('Limpeza', 'Estofados'),
  ('Limpeza', 'Vidros'),
  ('Limpeza', 'Caixa-d’água'),
  ('Limpeza', 'Limpeza pesada'),
  ('Lavanderia e passadoria', 'Lavar roupas'),
  ('Lavanderia e passadoria', 'Passar roupas'),
  ('Lavanderia e passadoria', 'Lavagem de tapetes'),
  ('Lavanderia e passadoria', 'Lavagem de cortinas'),
  ('Organização', 'Organização residencial'),
  ('Organização', 'Mudança e desempacotamento'),
  ('Organização', 'Organização de armários'),
  ('Organização', 'Descarte e doação'),
  ('Culinária doméstica', 'Cozinheiro em domicílio'),
  ('Culinária doméstica', 'Marmitas'),
  ('Culinária doméstica', 'Churrasqueiro'),
  ('Culinária doméstica', 'Bolos e doces'),
  ('Culinária doméstica', 'Congelados'),
  ('Mudanças e transporte', 'Mudança residencial'),
  ('Mudanças e transporte', 'Carreto'),
  ('Mudanças e transporte', 'Frete leve'),
  ('Mudanças e transporte', 'Montagem na mudança'),
  ('Mudanças e transporte', 'Guarda-móveis'),
  ('Automotivo', 'Lavagem de carro'),
  ('Automotivo', 'Higienização interna'),
  ('Automotivo', 'Diagnóstico automotivo'),
  ('Automotivo', 'Polimento'),
  ('Automotivo', 'Lavagem ecológica'),
  ('Mecânica automotiva', 'Socorro mecânico'),
  ('Mecânica automotiva', 'Revisão'),
  ('Mecânica automotiva', 'Freios'),
  ('Mecânica automotiva', 'Suspensão'),
  ('Mecânica automotiva', 'Motor'),
  ('Mecânica automotiva', 'Troca de óleo'),
  ('Elétrica automotiva', 'Bateria'),
  ('Elétrica automotiva', 'Alternador'),
  ('Elétrica automotiva', 'Partida'),
  ('Elétrica automotiva', 'Iluminação automotiva'),
  ('Elétrica automotiva', 'Diagnóstico elétrico automotivo'),
  ('Pneus e rodas', 'Borracharia móvel'),
  ('Pneus e rodas', 'Troca de pneu'),
  ('Pneus e rodas', 'Alinhamento e balanceamento'),
  ('Pneus e rodas', 'Reparo de roda'),
  ('Motos e bicicletas', 'Manutenção de moto'),
  ('Motos e bicicletas', 'Lavagem de moto'),
  ('Motos e bicicletas', 'Manutenção de bicicleta'),
  ('Motos e bicicletas', 'Montagem de bicicleta'),
  ('Casa e utensílios', 'Alças e cabos de panela'),
  ('Casa e utensílios', 'Afiação'),
  ('Casa e utensílios', 'Tampas e utensílios'),
  ('Casa e utensílios', 'Conserto de cadeira'),
  ('Casa e utensílios', 'Puxadores e dobradiças'),
  ('Costura e acessórios', 'Ajustes e bainhas'),
  ('Costura e acessórios', 'Zíperes'),
  ('Costura e acessórios', 'Calçados e bolsas'),
  ('Costura e acessórios', 'Botões'),
  ('Costura e acessórios', 'Reparo de mochila e mala'),
  ('Relógios e joias', 'Troca de bateria'),
  ('Relógios e joias', 'Ajuste de pulseira'),
  ('Relógios e joias', 'Reparo de relógio'),
  ('Relógios e joias', 'Limpeza e reparo de joia'),
  ('Instrumentos musicais', 'Regulagem'),
  ('Instrumentos musicais', 'Troca de cordas'),
  ('Instrumentos musicais', 'Reparo eletrônico'),
  ('Instrumentos musicais', 'Afinação de piano'),
  ('Beleza', 'Cabelo'),
  ('Beleza', 'Manicure e pedicure'),
  ('Beleza', 'Maquiagem'),
  ('Beleza', 'Barbearia'),
  ('Beleza', 'Design de sobrancelhas'),
  ('Beleza', 'Depilação'),
  ('Bem-estar', 'Massagem'),
  ('Bem-estar', 'Personal trainer'),
  ('Bem-estar', 'Yoga e alongamento'),
  ('Bem-estar', 'Meditação'),
  ('Saúde', 'Enfermagem domiciliar'),
  ('Saúde', 'Fisioterapia'),
  ('Saúde', 'Psicologia'),
  ('Saúde', 'Nutrição'),
  ('Saúde', 'Fonoaudiologia'),
  ('Saúde', 'Terapia ocupacional'),
  ('Cuidados pessoais', 'Cuidador de idoso'),
  ('Cuidados pessoais', 'Acompanhante hospitalar'),
  ('Cuidados pessoais', 'Babá'),
  ('Cuidados pessoais', 'Cuidador de pessoa com deficiência'),
  ('Cuidados com pets', 'Passeio'),
  ('Cuidados com pets', 'Pet sitter'),
  ('Cuidados com pets', 'Banho e tosa'),
  ('Cuidados com pets', 'Transporte pet'),
  ('Cuidados com pets', 'Hospedagem domiciliar'),
  ('Saúde animal', 'Consulta veterinária domiciliar'),
  ('Saúde animal', 'Vacinação'),
  ('Saúde animal', 'Curativos'),
  ('Saúde animal', 'Fisioterapia animal'),
  ('Treinamento de pets', 'Adestramento'),
  ('Treinamento de pets', 'Correção de comportamento'),
  ('Treinamento de pets', 'Socialização'),
  ('Aulas particulares', 'Reforço escolar'),
  ('Aulas particulares', 'Matemática'),
  ('Aulas particulares', 'Português'),
  ('Aulas particulares', 'Física'),
  ('Aulas particulares', 'Química'),
  ('Aulas particulares', 'Redação'),
  ('Idiomas', 'Inglês'),
  ('Idiomas', 'Espanhol'),
  ('Idiomas', 'Alemão'),
  ('Idiomas', 'Português para estrangeiros'),
  ('Idiomas', 'Conversação'),
  ('Música e artes', 'Violão e guitarra'),
  ('Música e artes', 'Teclado e piano'),
  ('Música e artes', 'Canto'),
  ('Música e artes', 'Desenho e pintura'),
  ('Música e artes', 'Dança'),
  ('Tecnologia e carreira', 'Informática básica'),
  ('Tecnologia e carreira', 'Planilhas'),
  ('Tecnologia e carreira', 'Preparação para entrevista'),
  ('Tecnologia e carreira', 'Currículo'),
  ('Tecnologia e carreira', 'Concursos'),
  ('Fotografia', 'Ensaio pessoal'),
  ('Fotografia', 'Fotografia de produto'),
  ('Fotografia', 'Fotografia imobiliária'),
  ('Fotografia', 'Fotografia gastronômica'),
  ('Fotografia', 'Cobertura de evento'),
  ('Fotografia', 'Foto 3x4 e documentos'),
  ('Fotografia', 'Tratamento de imagens'),
  ('Produção audiovisual', 'Filmagem'),
  ('Produção audiovisual', 'Vídeo institucional'),
  ('Produção audiovisual', 'Vídeo para redes sociais'),
  ('Produção audiovisual', 'Captação com drone'),
  ('Produção audiovisual', 'Edição de vídeo'),
  ('Produção audiovisual', 'Animação e motion design'),
  ('Produção audiovisual', 'Podcast e videocast'),
  ('Design e mídia digital', 'Identidade visual'),
  ('Design e mídia digital', 'Logotipo'),
  ('Design e mídia digital', 'Artes para redes sociais'),
  ('Design e mídia digital', 'Apresentações'),
  ('Design e mídia digital', 'Diagramação'),
  ('Design e mídia digital', 'Ilustração'),
  ('Design e mídia digital', 'Modelagem 3D'),
  ('Design e mídia digital', 'UI e UX'),
  ('Conteúdo digital', 'Produção de conteúdo'),
  ('Conteúdo digital', 'Roteiro'),
  ('Conteúdo digital', 'Copywriting'),
  ('Conteúdo digital', 'Gestão de redes sociais'),
  ('Conteúdo digital', 'Calendário editorial'),
  ('Conteúdo digital', 'Revisão de conteúdo'),
  ('Conteúdo digital', 'Legendagem'),
  ('Áudio e transmissão', 'Locução'),
  ('Áudio e transmissão', 'Gravação e edição de áudio'),
  ('Áudio e transmissão', 'Mixagem e masterização'),
  ('Áudio e transmissão', 'Trilha sonora'),
  ('Áudio e transmissão', 'Transmissão ao vivo'),
  ('Áudio e transmissão', 'Operação de streaming'),
  ('Alimentação para eventos', 'Buffet'),
  ('Alimentação para eventos', 'Churrasqueiro'),
  ('Alimentação para eventos', 'Bartender'),
  ('Alimentação para eventos', 'Doces e bolos'),
  ('Alimentação para eventos', 'Garçom'),
  ('Foto e vídeo', 'Fotografia'),
  ('Foto e vídeo', 'Filmagem'),
  ('Foto e vídeo', 'Drone'),
  ('Foto e vídeo', 'Edição de evento'),
  ('Foto e vídeo', 'Cabine de fotos'),
  ('Som e entretenimento', 'DJ'),
  ('Som e entretenimento', 'Som e iluminação'),
  ('Som e entretenimento', 'Música ao vivo'),
  ('Som e entretenimento', 'Recreação infantil'),
  ('Som e entretenimento', 'Cerimonial'),
  ('Decoração e estrutura', 'Decoração'),
  ('Decoração e estrutura', 'Balões'),
  ('Decoração e estrutura', 'Mesas e cadeiras'),
  ('Decoração e estrutura', 'Tendas'),
  ('Decoração e estrutura', 'Gerador para evento'),
  ('Apoio administrativo', 'Assistente virtual'),
  ('Apoio administrativo', 'Digitação'),
  ('Apoio administrativo', 'Organização de documentos'),
  ('Apoio administrativo', 'Atendimento ao cliente'),
  ('Contabilidade e finanças', 'Abertura de empresa'),
  ('Contabilidade e finanças', 'Imposto de renda'),
  ('Contabilidade e finanças', 'Contabilidade mensal'),
  ('Contabilidade e finanças', 'Planejamento financeiro empresarial'),
  ('Serviços jurídicos', 'Consulta jurídica'),
  ('Serviços jurídicos', 'Contratos'),
  ('Serviços jurídicos', 'Direito do consumidor'),
  ('Serviços jurídicos', 'Direito trabalhista'),
  ('Serviços jurídicos', 'Mediação'),
  ('Marketing e comunicação', 'Social media'),
  ('Marketing e comunicação', 'Tráfego pago'),
  ('Marketing e comunicação', 'Identidade visual'),
  ('Marketing e comunicação', 'Redação'),
  ('Marketing e comunicação', 'Assessoria de imprensa'),
  ('Tradução e conteúdo', 'Tradução'),
  ('Tradução e conteúdo', 'Revisão de texto'),
  ('Tradução e conteúdo', 'Transcrição'),
  ('Tradução e conteúdo', 'Legendagem'),
  ('Engenharia especializada', 'Projetos'),
  ('Engenharia especializada', 'Inspeções e laudos'),
  ('Engenharia especializada', 'Subestações'),
  ('Engenharia especializada', 'SPDA'),
  ('Engenharia especializada', 'Eficiência energética'),
  ('Engenharia especializada', 'BIM e modelagem'),
  ('Arquitetura e interiores', 'Projeto arquitetônico'),
  ('Arquitetura e interiores', 'Design de interiores'),
  ('Arquitetura e interiores', 'Regularização'),
  ('Arquitetura e interiores', 'Acompanhamento de obra'),
  ('Segurança do trabalho', 'Treinamentos'),
  ('Segurança do trabalho', 'Documentação'),
  ('Segurança do trabalho', 'Inspeção'),
  ('Segurança do trabalho', 'Consultoria'),
  ('Serviços rápidos', 'Fila e despachante'),
  ('Serviços rápidos', 'Compras e entregas'),
  ('Serviços rápidos', 'Montagem de cesta'),
  ('Serviços rápidos', 'Ajuda com mudança pequena')
on conflict do nothing;

alter table public.service_taxonomy enable row level security;
create policy service_taxonomy_read on public.service_taxonomy for select to authenticated using (true);
revoke all on public.service_taxonomy from anon, authenticated;
grant select on public.service_taxonomy to authenticated;

-- NOT VALID aplica a regra a novas inserções sem apagar ofertas legadas.
alter table public.provider_services add constraint provider_services_taxonomy_fk
  foreign key (category, subcategory) references public.service_taxonomy(category, subcategory) not valid;
