const professionals=[
{id:1,name:'Rafael Lima',initials:'RL',category:'Elétrica',icon:'⚡',color:'#fff0ce',rating:4.9,reviews:48,jobs:62,areas:['Tarumã','Ponta Negra','Centro'],services:[['Troca de tomada',85,'Mão de obra para uma tomada em ponto existente. Peça não incluída.'],['Instalação de luminária',120,'Uma luminária em ponto existente. Luminária fornecida pelo cliente.']]},
{id:2,name:'Camila Souza',initials:'CS',category:'Limpeza',icon:'✦',color:'#eee6ff',rating:4.8,reviews:73,jobs:95,areas:['Tarumã','Ponta Negra','Adrianópolis'],services:[['Limpeza residencial • 4 horas',160,'Limpeza de rotina por até quatro horas. Produtos fornecidos pelo cliente.']]},
{id:3,name:'Bruno Martins',initials:'BM',category:'Climatização',icon:'❄',color:'#e0f4f3',rating:4.9,reviews:36,jobs:45,areas:['Tarumã','Parque 10','Novo Aleixo'],services:[['Limpeza de split até 12.000 BTU',180,'Uma unidade com acesso facilitado. Reparos e peças não incluídos.'],['Visita de diagnóstico',90,'Avaliação de uma unidade. Reparos recebem orçamento separado.']]},
{id:4,name:'Diego Alves',initials:'DA',category:'Hidráulica',icon:'💧',color:'#e5edff',rating:4.7,reviews:29,jobs:38,areas:['Centro','Adrianópolis','Parque 10'],services:[['Troca de torneira',95,'Uma torneira em instalação existente. Peça fornecida pelo cliente.']]},
{id:5,name:'Juliana Costa',initials:'JC',category:'Montagem',icon:'🔧',color:'#ffe7de',rating:4.8,reviews:52,jobs:70,areas:['Ponta Negra','Tarumã','Centro'],services:[['Montagem de mesa simples',130,'Uma mesa desmontada, com peças e manual disponíveis.']]},
{id:6,name:'André Rocha',initials:'AR',category:'Elétrica',icon:'⚡',color:'#fff0ce',rating:null,reviews:0,jobs:0,areas:['Novo Aleixo','Parque 10','Adrianópolis'],services:[['Visita de diagnóstico elétrico',100,'Avaliação inicial. Execução e materiais não incluídos.']]}
];
const $=s=>document.querySelector(s),money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let category='Todos',orders=[];try{const saved=JSON.parse(localStorage.getItem('sx-demo-v1')||'[]');if(Array.isArray(saved))orders=saved.filter(o=>professionals.some(p=>p.id===o.pid)&&['Solicitado','Confirmado','Em execução','Concluído','Cancelado'].includes(o.status)&&Number.isFinite(o.base));}catch{}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem('sx-demo-v1',JSON.stringify(orders));}catch{toast('O navegador não permitiu salvar. Mantenha esta aba aberta.');}$('#badge').textContent=orders.length;}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500);}
function modal(html){$('#modalBody').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function total(base){return Math.round(base*1.1*100)/100;}
function render(){const q=normalize($('#query').value),area=$('#district').value,min=Number($('#rating').value);let list=professionals.filter(p=>(category==='Todos'||p.category===category)&&(!area||atendeBairro(p.areas,area))&&(!min||(p.rating||0)>=min)&&normalize(p.name+' '+p.category+' '+p.services.flat().join(' ')).includes(q));const sort=$('#sort').value;list.sort(sort==='price'?(a,b)=>Math.min(...a.services.map(s=>s[1]))-Math.min(...b.services.map(s=>s[1])):sort==='rating'?(a,b)=>(b.rating||0)-(a.rating||0)||b.reviews-a.reviews:(a,b)=>((b.rating||0)*b.reviews/(b.reviews+10))-((a.rating||0)*a.reviews/(a.reviews+10)));$('#count').textContent=`${list.length} profissionais encontrados${area?' • Atendem '+area:''}`;$('#cards').innerHTML=list.map(p=>`<article class="card"><div class="cover" style="background:${p.color}"><span class="icon">${p.icon}</span><span class="label">${p.category}</span></div><div class="card-body"><div class="identity"><span class="avatar">${p.initials}</span><div><h3>${p.name}</h3><span class="stars">${p.rating?'★ '+p.rating.toFixed(1).replace('.',',')+' · '+p.reviews+' avaliações':'Novo na plataforma'}</span></div></div><p>${p.services[0][0]}</p><div class="tags">◉ Atende ${p.areas.join(' · ')}</div><div class="price-row"><div><small>Preço inicial total · demonstrativo</small><strong>${money(total(Math.min(...p.services.map(s=>s[1]))))}</strong></div><button data-profile="${p.id}">Ver serviços ↗</button></div></div></article>`).join('')||'<div class="empty"><h3>Nenhum profissional com esses filtros.</h3><p>Tente outro bairro ou reduza a nota mínima.</p></div>';}
function profile(id){const p=professionals.find(p=>p.id===id);modal(`<span class="eyebrow">PERFIL DEMONSTRATIVO • ${p.category}</span><h2>${p.name}</h2><p>${p.rating?'★ '+p.rating+' · '+p.reviews+' avaliações':'Novo na plataforma'} · ${p.jobs} serviços concluídos</p><p class="hint">Atende: ${p.areas.join(', ')}. Valores e reputação fictícios.</p>${p.services.map((s,i)=>`<div class="service"><h3>${s[0]}</h3><p>${s[2]}</p><b>${money(total(s[1]))} — total demonstrativo</b><br><button class="primary" data-book="${p.id}:${i}">Solicitar serviço</button></div>`).join('')}`);}
function booking(id,index){const p=professionals.find(p=>p.id===id),s=p.services[index];modal(`<span class="eyebrow">SIMULAR CONTRATAÇÃO</span><h2>${s[0]}</h2><p>Com ${p.name}</p><p class="hint">${s[2]}</p><form id="bookForm"><label>Bairro<select id="bookArea" required>${p.areas.map(a=>`<option${a===$('#district').value?' selected':''}>${a}</option>`).join('')}</select></label><label>Data desejada<input id="bookDate" type="date" required></label><label>Período<select id="bookTime"><option>Manhã</option><option>Tarde</option></select></label><div class="bill"><div><span>Valor do profissional</span><b>${money(s[1])}</b></div><div><span>Taxa ilustrativa de 10%</span><b>${money(total(s[1])-s[1])}</b></div><div><strong>Total</strong><strong>${money(total(s[1]))}</strong></div></div><p class="hint">Taxa apenas para testar a interface, não definida comercialmente. Nenhum pagamento será efetuado. Data sujeita à confirmação.</p><button class="primary" type="submit">Criar pedido demonstrativo</button></form>`);const now=new Date(),today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');$('#bookDate').min=today;$('#bookForm').onsubmit=e=>{e.preventDefault();if($('#bookDate').value<today)return;const codes=new Uint32Array(2);crypto.getRandomValues(codes);const start=String(100000+codes[0]%900000);let finish=String(100000+codes[1]%900000);if(finish===start)finish=String(Number(start)===999999?100000:Number(start)+1);orders.unshift({id:Date.now(),pid:id,service:s[0],base:s[1],area:$('#bookArea').value,date:$('#bookDate').value,time:$('#bookTime').value,status:'Solicitado',start,finish});persist();showOrders();toast('Pedido demonstrativo criado.');};}
function showOrders(){modal(`<span class="eyebrow">ÁREA DE DEMONSTRAÇÃO</span><h2>Meus pedidos</h2><p class="hint">Você simula os dois lados do atendimento. Os códigos ficam neste navegador: não são um mecanismo de segurança para produção.</p>${orders.length?orders.map(o=>`<article class="order"><span class="status">${o.status}</span><h3>${esc(o.service)}</h3><p>${professionals.find(p=>p.id===o.pid).name} · ${esc(o.area)}<br>${esc(o.date.split('-').reverse().join('/'))} · ${esc(o.time)}</p><b>${money(total(o.base))}</b>${o.status==='Solicitado'?`<p><button class="primary" data-confirm="${o.id}">Simular aceite do profissional</button></p>`:''}${['Confirmado','Em execução'].includes(o.status)?`<p class="hint">Código de ${o.status==='Confirmado'?'início':'conclusão'} do cliente: <b>${o.status==='Confirmado'?o.start:o.finish}</b></p><form data-transition="${o.id}"><label>Simular profissional: digite o código<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="off"></label><button class="primary" type="submit">${o.status==='Confirmado'?'Iniciar serviço':'Concluir serviço'}</button></form>`:''}${['Solicitado','Confirmado'].includes(o.status)?`<button class="secondary" data-cancel="${o.id}">Cancelar simulação</button>`:''}${o.status==='Concluído'?'<p class="hint">Fluxo concluído. Nenhum valor foi cobrado ou repassado.</p>':''}</article>`).join(''):'<div class="empty">Você ainda não tem pedidos. Explore os serviços para começar.</div>'}`);}
$('#categories').innerHTML=['Todos','Elétrica','Climatização','Limpeza','Hidráulica','Montagem'].map(c=>`<button data-category="${c}" class="${c==='Todos'?'active':''}">${c}</button>`).join('');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.category){category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x.dataset.category===category));render();}if(b.dataset.profile)profile(Number(b.dataset.profile));if(b.dataset.book)booking(...b.dataset.book.split(':').map(Number));if(b.dataset.confirm){const o=orders.find(o=>o.id===Number(b.dataset.confirm));if(o.status==='Solicitado'){o.status='Confirmado';persist();showOrders();}}if(b.dataset.cancel){const o=orders.find(o=>o.id===Number(b.dataset.cancel));if(['Solicitado','Confirmado'].includes(o.status)){o.status='Cancelado';persist();showOrders();}}});
document.addEventListener('submit',e=>{if(!e.target.dataset.transition)return;e.preventDefault();const o=orders.find(o=>o.id===Number(e.target.dataset.transition));if(!['Confirmado','Em execução'].includes(o.status))return;const expected=o.status==='Confirmado'?o.start:o.finish;if(e.target.elements.code.value!==expected){toast('Código incorreto. Confira o código demonstrativo.');return;}o.status=o.status==='Confirmado'?'Em execução':'Concluído';persist();showOrders();});
['query','district','rating','sort'].forEach(id=>$('#'+id).addEventListener(id==='query'?'input':'change',render));$('#reset').onclick=()=>{$('#query').value='';$('#district').value='';$('#rating').value='0';$('#sort').value='recommended';document.querySelector('[data-category="Todos"]').click();};$('#close').onclick=()=>$('#modal').close();$('#ordersButton').onclick=showOrders;$('#explore').onclick=()=>$('#catalog').scrollIntoView({behavior:'smooth'});render();
