/* Catálogo extensível do protótipo. Categorias sem oferta continuam pesquisáveis para sugestões. */
const SERVICE_CATALOG=Object.freeze([
{group:'Casa e manutenção',nature:'essential',category:'Elétrica',subs:['Tomadas e interruptores','Iluminação','Ventiladores','Diagnóstico elétrico','Quadros','Chuveiros','Fiação e circuitos','Padrão de entrada','Aterramento e proteção','Geradores e nobreaks']},
{group:'Casa e manutenção',nature:'essential',category:'Hidráulica',subs:['Torneiras','Vazamentos','Vasos e descargas','Caixas-d’água','Sifões e ralos','Bombas d’água','Tubulações','Desentupimento']},
{group:'Casa e manutenção',nature:'essential',category:'Climatização',subs:['Limpeza de split','Instalação','Diagnóstico de ar-condicionado','Manutenção preventiva','Reparo de ar-condicionado','Climatização comercial']},
{group:'Casa e manutenção',nature:'regulated',category:'Gás residencial',subs:['Inspeção de instalação','Detecção de vazamento','Instalação de ponto de gás','Conversão de aparelho']},
{group:'Casa e manutenção',nature:'regular',category:'Montagem',subs:['Móveis','Prateleiras e suportes','Cortinas e varais','Suportes de TV','Equipamentos de academia']},
{group:'Casa e manutenção',nature:'regular',category:'Pintura e reparos',subs:['Pintura','Portas e ferragens','Vedação','Textura e acabamento','Papel de parede','Pequenos reparos']},
{group:'Casa e manutenção',nature:'regular',category:'Reforma e construção',subs:['Alvenaria','Pisos e revestimentos','Gesso e drywall','Forro','Impermeabilização','Demolição controlada','Reforma de cômodo']},
{group:'Casa e manutenção',nature:'regular',category:'Marcenaria',subs:['Móveis sob medida','Reparo de móveis','Portas de madeira','Ajuste de gavetas e dobradiças']},
{group:'Casa e manutenção',nature:'regular',category:'Serralheria',subs:['Portões e grades','Soldagem','Estruturas metálicas','Corrimãos']},
{group:'Casa e manutenção',nature:'regular',category:'Vidraçaria',subs:['Vidros e espelhos','Box de banheiro','Janelas de vidro','Tampos de mesa']},
{group:'Casa e manutenção',nature:'essential',category:'Telhados e calhas',subs:['Reparo de telhado','Limpeza de calhas','Instalação de calhas','Detecção de infiltração']},
{group:'Casa e manutenção',nature:'essential',category:'Chaveiro e acesso',subs:['Abertura de porta','Troca de fechadura','Cópia de chaves','Fechadura digital','Controle de portão']},
{group:'Casa e manutenção',nature:'essential',category:'Dedetização',subs:['Insetos rasteiros','Cupins','Roedores','Limpeza de caixa-d’água','Controle de pragas']},
{group:'Casa e manutenção',nature:'regular',category:'Jardim e piscina',subs:['Jardinagem','Poda','Paisagismo','Limpeza de piscina','Manutenção de piscina','Irrigação']},
{group:'Casa e manutenção',nature:'regulated',category:'Energia solar',subs:['Projeto fotovoltaico','Instalação solar','Limpeza de módulos','Diagnóstico e manutenção','Homologação']},
{group:'Tecnologia',nature:'essential',category:'Internet e redes',subs:['Roteadores e Wi-Fi','Rede mesh','Cabeamento e pontos de rede','Fibra óptica interna','Diagnóstico de conexão']},
{group:'Tecnologia',nature:'regular',category:'Celulares e eletrônicos',subs:['Celulares e tablets','Computadores e notebooks','TVs e monitores','Videogames e controles','Áudio e eletrônicos','Pequenos eletrodomésticos','Impressoras']},
{group:'Tecnologia',nature:'essential',category:'Segurança eletrônica',subs:['Câmeras e CFTV','Alarmes','Interfone','Cerca elétrica','Controle de acesso']},
{group:'Tecnologia',nature:'regular',category:'Casa inteligente',subs:['Automação residencial','Assistentes de voz','Iluminação inteligente','Sensores e fechaduras']},
{group:'Tecnologia',nature:'regular',category:'Serviços digitais',subs:['Criação de site','Suporte remoto','Configuração de e-mail','Recuperação de dados','Design gráfico','Edição de vídeo']},
{group:'Limpeza e cuidados',nature:'essential',category:'Limpeza',subs:['Residencial','Comercial','Pós-obra','Estofados','Vidros','Caixa-d’água','Limpeza pesada']},
{group:'Limpeza e cuidados',nature:'regular',category:'Lavanderia e passadoria',subs:['Lavar roupas','Passar roupas','Lavagem de tapetes','Lavagem de cortinas']},
{group:'Limpeza e cuidados',nature:'regular',category:'Organização',subs:['Organização residencial','Mudança e desempacotamento','Organização de armários','Descarte e doação']},
{group:'Limpeza e cuidados',nature:'regular',category:'Culinária doméstica',subs:['Cozinheiro em domicílio','Marmitas','Churrasqueiro','Bolos e doces','Congelados']},
{group:'Limpeza e cuidados',nature:'essential',category:'Mudanças e transporte',subs:['Mudança residencial','Carreto','Frete leve','Montagem na mudança','Guarda-móveis']},
{group:'Automotivo',nature:'regular',category:'Automotivo',subs:['Lavagem de carro','Higienização interna','Diagnóstico automotivo','Polimento','Lavagem ecológica']},
{group:'Automotivo',nature:'essential',category:'Mecânica automotiva',subs:['Socorro mecânico','Revisão','Freios','Suspensão','Motor','Troca de óleo']},
{group:'Automotivo',nature:'essential',category:'Elétrica automotiva',subs:['Bateria','Alternador','Partida','Iluminação automotiva','Diagnóstico elétrico automotivo']},
{group:'Automotivo',nature:'essential',category:'Pneus e rodas',subs:['Borracharia móvel','Troca de pneu','Alinhamento e balanceamento','Reparo de roda']},
{group:'Automotivo',nature:'regular',category:'Motos e bicicletas',subs:['Manutenção de moto','Lavagem de moto','Manutenção de bicicleta','Montagem de bicicleta']},
{group:'Pequenos consertos',nature:'regular',category:'Casa e utensílios',subs:['Alças e cabos de panela','Afiação','Tampas e utensílios','Conserto de cadeira','Puxadores e dobradiças']},
{group:'Pequenos consertos',nature:'regular',category:'Costura e acessórios',subs:['Ajustes e bainhas','Zíperes','Calçados e bolsas','Botões','Reparo de mochila e mala']},
{group:'Pequenos consertos',nature:'regular',category:'Relógios e joias',subs:['Troca de bateria','Ajuste de pulseira','Reparo de relógio','Limpeza e reparo de joia']},
{group:'Pequenos consertos',nature:'regular',category:'Instrumentos musicais',subs:['Regulagem','Troca de cordas','Reparo eletrônico','Afinação de piano']},
{group:'Beleza e bem-estar',nature:'regular',category:'Beleza',subs:['Cabelo','Manicure e pedicure','Maquiagem','Barbearia','Design de sobrancelhas','Depilação']},
{group:'Beleza e bem-estar',nature:'regular',category:'Bem-estar',subs:['Massagem','Personal trainer','Yoga e alongamento','Meditação']},
{group:'Beleza e bem-estar',nature:'regulated',category:'Saúde',subs:['Enfermagem domiciliar','Fisioterapia','Psicologia','Nutrição','Fonoaudiologia','Terapia ocupacional']},
{group:'Beleza e bem-estar',nature:'essential',category:'Cuidados pessoais',subs:['Cuidador de idoso','Acompanhante hospitalar','Babá','Cuidador de pessoa com deficiência']},
{group:'Pets',nature:'essential',category:'Cuidados com pets',subs:['Passeio','Pet sitter','Banho e tosa','Transporte pet','Hospedagem domiciliar']},
{group:'Pets',nature:'regulated',category:'Saúde animal',subs:['Consulta veterinária domiciliar','Vacinação','Curativos','Fisioterapia animal']},
{group:'Pets',nature:'regular',category:'Treinamento de pets',subs:['Adestramento','Correção de comportamento','Socialização']},
{group:'Educação',nature:'regular',category:'Aulas particulares',subs:['Reforço escolar','Matemática','Português','Física','Química','Redação']},
{group:'Educação',nature:'regular',category:'Idiomas',subs:['Inglês','Espanhol','Alemão','Português para estrangeiros','Conversação']},
{group:'Educação',nature:'regular',category:'Música e artes',subs:['Violão e guitarra','Teclado e piano','Canto','Desenho e pintura','Dança']},
{group:'Educação',nature:'regular',category:'Tecnologia e carreira',subs:['Informática básica','Planilhas','Preparação para entrevista','Currículo','Concursos']},
{group:'Mídia e criatividade',nature:'regular',category:'Fotografia',subs:['Ensaio pessoal','Fotografia de produto','Fotografia imobiliária','Fotografia gastronômica','Cobertura de evento','Foto 3x4 e documentos','Tratamento de imagens']},
{group:'Mídia e criatividade',nature:'regular',category:'Produção audiovisual',subs:['Filmagem','Vídeo institucional','Vídeo para redes sociais','Captação com drone','Edição de vídeo','Animação e motion design','Podcast e videocast']},
{group:'Mídia e criatividade',nature:'regular',category:'Design e mídia digital',subs:['Identidade visual','Logotipo','Artes para redes sociais','Apresentações','Diagramação','Ilustração','Modelagem 3D','UI e UX']},
{group:'Mídia e criatividade',nature:'regular',category:'Conteúdo digital',subs:['Produção de conteúdo','Roteiro','Copywriting','Gestão de redes sociais','Calendário editorial','Revisão de conteúdo','Legendagem']},
{group:'Mídia e criatividade',nature:'regular',category:'Áudio e transmissão',subs:['Locução','Gravação e edição de áudio','Mixagem e masterização','Trilha sonora','Transmissão ao vivo','Operação de streaming']},
{group:'Eventos',nature:'regular',category:'Alimentação para eventos',subs:['Buffet','Churrasqueiro','Bartender','Doces e bolos','Garçom']},
{group:'Eventos',nature:'regular',category:'Foto e vídeo',subs:['Fotografia','Filmagem','Drone','Edição de evento','Cabine de fotos']},
{group:'Eventos',nature:'regular',category:'Som e entretenimento',subs:['DJ','Som e iluminação','Música ao vivo','Recreação infantil','Cerimonial']},
{group:'Eventos',nature:'regular',category:'Decoração e estrutura',subs:['Decoração','Balões','Mesas e cadeiras','Tendas','Gerador para evento']},
{group:'Empresas',nature:'regular',category:'Apoio administrativo',subs:['Assistente virtual','Digitação','Organização de documentos','Atendimento ao cliente']},
{group:'Empresas',nature:'regulated',category:'Contabilidade e finanças',subs:['Abertura de empresa','Imposto de renda','Contabilidade mensal','Planejamento financeiro empresarial']},
{group:'Empresas',nature:'regulated',category:'Serviços jurídicos',subs:['Consulta jurídica','Contratos','Direito do consumidor','Direito trabalhista','Mediação']},
{group:'Empresas',nature:'regular',category:'Marketing e comunicação',subs:['Social media','Tráfego pago','Identidade visual','Redação','Assessoria de imprensa']},
{group:'Empresas',nature:'regular',category:'Tradução e conteúdo',subs:['Tradução','Revisão de texto','Transcrição','Legendagem']},
{group:'Serviços especializados',nature:'regulated',category:'Engenharia especializada',subs:['Projetos','Inspeções e laudos','Subestações','SPDA','Eficiência energética','BIM e modelagem']},
{group:'Serviços especializados',nature:'regulated',category:'Arquitetura e interiores',subs:['Projeto arquitetônico','Design de interiores','Regularização','Acompanhamento de obra']},
{group:'Serviços especializados',nature:'regulated',category:'Segurança do trabalho',subs:['Treinamentos','Documentação','Inspeção','Consultoria']},
{group:'Serviços especializados',nature:'regular',category:'Serviços rápidos',subs:['Fila e despachante','Compras e entregas','Montagem de cesta','Ajuda com mudança pequena']}
]);
const SERVICE_GROUPS=Object.freeze([...new Set(SERVICE_CATALOG.map(x=>x.group))]);
const SERVICE_NATURE_LABELS=Object.freeze({essential:'Essenciais e urgentes',regular:'Outros serviços',regulated:'Regulados e especializados'});
const taxonomy=Object.fromEntries(SERVICE_CATALOG.map(x=>[x.category,x.subs]));
function categoryMeta(category){return SERVICE_CATALOG.find(x=>x.category===category)||null;}
