/* Organização da interface. Não migra nem regrava dados locais. */
const groupIcons={'Casa e manutenção':'⌂','Tecnologia':'⌘','Limpeza e cuidados':'✦','Automotivo':'◉','Pequenos consertos':'⚒','Beleza e bem-estar':'♡','Pets':'♧','Educação':'◫','Mídia e criatividade':'◈','Eventos':'♫','Empresas':'▦','Serviços especializados':'▧'};
const serviceGroups=SERVICE_GROUPS.map(name=>[name,groupIcons[name]||'•',SERVICE_CATALOG.filter(x=>x.group===name).map(x=>x.category)]);
let selectedGroup='',orderTab='active';
$('.hero').innerHTML='<div><span class="eyebrow">SERVIÇOS EM MANAUS</span><h1>O que você precisa <em>resolver?</em></h1><p>Do pequeno conserto à manutenção da casa. Encontre quem atende seu bairro.</p></div><div class="hero-stamp" aria-hidden="true">s↗</div>';
const filterBox=$('.filters');filterBox.classList.add('discovery');
const natureLabel=document.createElement('label');natureLabel.textContent='Tipo de serviço';natureLabel.innerHTML+=' <select id="nature"><option value="">Todos</option><option value="essential">Essenciais e urgentes</option><option value="regular">Outros serviços</option><option value="regulated">Regulados e especializados</option></select>';filterBox.append(natureLabel);
$('.hero').insertAdjacentElement('afterend',filterBox);
$('#query').placeholder='Ex.: panela, celular, luminária…';
$('#query').type='search';$('#query').closest('label').firstChild.textContent='Qual serviço você procura?';
$('#district').closest('label').firstChild.textContent='Onde será o atendimento?';
const advanced=document.createElement('details');advanced.className='advanced-filters';advanced.innerHTML='<summary>Mais filtros</summary><div class="advanced-fields"></div>';
['rating','modality','nature','sort'].forEach(id=>advanced.lastElementChild.append($('#'+id).closest('label')));filterBox.append(advanced);
$('#catalog .section-head h2').textContent='Encontre por categoria';
$('#catalog .section-head .eyebrow').textContent='EXPLORE AS POSSIBILIDADES';
$('#categories').insertAdjacentHTML('beforebegin','<div id="groupGrid" class="group-grid" aria-label="Grupos de serviços"></div>');
$('#subs').insertAdjacentHTML('afterend','<div id="filterChips" class="filter-chips" aria-label="Filtros selecionados"></div>');
function drawGroups(){ $('#groupGrid').innerHTML=serviceGroups.map(([name,icon])=>`<button type="button" data-group="${esc(name)}" aria-pressed="${selectedGroup===name}" class="group-card ${selectedGroup===name?'selected':''}"><span aria-hidden="true">${icon}</span><b>${esc(name)}</b></button>`).join('');}
categoryTabs=function(){drawGroups();const group=serviceGroups.find(g=>g[0]===selectedGroup);const cats=group?group[2]:Object.keys(taxonomy);$('#categories').innerHTML=`<button type="button" data-all-services aria-pressed="${!selectedGroup&&category==='Todos'}">Todos os serviços</button>`+cats.map(c=>`<button type="button" data-cat2="${esc(c)}" aria-pressed="${category===c}" class="${category===c?'active':''}">${esc(c)}</button>`).join('');$('#subs').innerHTML=category==='Todos'?'':['Todos os subserviços',...taxonomy[category]].map((s,i)=>`<button type="button" data-sub2="${i?esc(s):''}" aria-pressed="${sub===(i?s:'')}" class="${sub===(i?s:'')?'active':''}">${esc(s)}</button>`).join('');};
function catalogEmptyCards(){const q=normalize($('#query').value.trim()),group=serviceGroups.find(g=>g[0]===selectedGroup),nature=$('#nature').value;const items=[];for(const meta of SERVICE_CATALOG){if(category!=='Todos'&&meta.category!==category)continue;if(group&&!group[2].includes(meta.category))continue;if(nature&&meta.nature!==nature)continue;for(const service of meta.subs){if(sub&&service!==sub)continue;if(q&&!normalize(meta.category+' '+service).includes(q))continue;items.push({meta,service});}}if(!items.length)return'<div class="empty"><h3>Não encontramos esse serviço no catálogo.</h3><p>Envie uma sugestão para avaliarmos a inclusão.</p><button class="primary" data-suggest2="1">Sugerir serviço</button></div>';return items.slice(0,24).map(({meta,service})=>`<article class="card unavailable-card"><div class="card-body"><span class="eyebrow">${esc(meta.group)}</span><h3 class="offer-title">${esc(service)}</h3><p>${esc(meta.category)} · ${esc(SERVICE_NATURE_LABELS[meta.nature])}</p><p class="hint">Ainda não há oferta demonstrativa para este serviço.</p><button class="primary" data-interest="${esc(service+' — '+meta.category)}">Tenho interesse</button></div></article>`).join('')+(items.length>24?`<p class="catalog-note">Mostrando 24 de ${items.length}. Refine a busca ou escolha uma categoria.</p>`:'');}
function relevantServices(p){const q=normalize($('#query').value.trim());return p.services.map((s,index)=>({s,index})).filter(({s})=>(!sub||s[3]===sub)&&(!q||normalize([p.name,p.category,...s].join(' ')).includes(q)));}
function chips(){const list=[];if(selectedGroup)list.push(['group',selectedGroup]);if(category!=='Todos')list.push(['category',category]);if(sub)list.push(['sub',sub]);for(const id of ['query','district','rating','modality','nature']){const el=$('#'+id);if(el.value&&el.value!=='0')list.push([id,id==='rating'?'Nota mínima '+el.value:el.value]);}$('#filterChips').innerHTML=list.map(([id,label])=>`<button type="button" data-clear-filter="${id}" aria-label="Remover filtro ${esc(label)}">${esc(label)} <span aria-hidden="true">×</span></button>`).join('');}
render=function(){categoryTabs();chips();const area=$('#district').value,min=Number($('#rating').value),mod=$('#modality').value,nature=$('#nature').value;const group=serviceGroups.find(g=>g[0]===selectedGroup);let offers=[];professionals.forEach(p=>{if(category!=='Todos'&&p.category!==category)return;if(group&&!group[2].includes(p.category))return;if(nature&&categoryMeta(p.category)?.nature!==nature)return;if(area&&!atendeBairro(p.areas,area))return;if(min&&(reputacao(p).media||0)<min)return;if(mod&&!p.modes.includes(mod))return;relevantServices(p).forEach(({s,index})=>offers.push({p,s,index}));});const score=p=>{const r=reputacao(p);return(r.media||0)*r.qtd/(r.qtd+10);};offers.sort((a,b)=>$('#sort').value==='price'?(a.s[1]??Infinity)-(b.s[1]??Infinity):$('#sort').value==='rating'?(reputacao(b.p).media||0)-(reputacao(a.p).media||0)||reputacao(b.p).qtd-reputacao(a.p).qtd:score(b.p)-score(a.p));$('#count').textContent=`${offers.length} serviços · ${new Set(offers.map(o=>o.p.id)).size} profissionais${area?' atendem '+area:''}`;$('#cards').innerHTML=offers.map(({p,s,index})=>`<article class="card offer-card"><div class="offer-top"><span class="offer-icon" aria-hidden="true">${esc(p.icon)}</span><span>${esc(p.category)}</span></div><div class="card-body"><h3 class="offer-title">${esc(s[0])}</h3><p class="offer-scope">${esc(s[2])}</p><div class="identity"><span class="avatar">${esc(p.initials)}</span><div><b>${esc(p.name)}</b><div class="stars">${esc(textoReputacao(p))}</div></div></div><p class="coverage">◉ ${area?'Atende '+esc(area):cobreManaus(p.areas)?'Atende toda Manaus':p.areas.slice(0,3).map(esc).join(' · ')+(p.areas.length>3?' e outros bairros':'')}</p><p class="offer-modes">${p.modes.map(esc).join(' / ')}</p><div class="price-row"><div><small>${s[1]===null?'Após avaliação':'Total demonstrativo deste serviço'}</small><strong>${s[1]===null?'Sob orçamento':money(total(s[1]))}</strong></div><button type="button" data-offer="${p.id}:${index}">Ver serviço ↗</button></div></div></article>`).join('')||catalogEmptyCards();};
function openOffer(id,index){const p=professionals.find(p=>p.id===id),s=p?.services[index];if(!s)return;modal(`<span class="eyebrow">${esc(p.category)} · OFERTA DEMONSTRATIVA</span><h2>${esc(s[0])}</h2><p><b>${esc(p.name)}</b> · ${esc(textoReputacao(p))}</p><div class="service"><h3>O que está incluído</h3><p>${esc(s[2])}</p><p>Modalidades: ${p.modes.map(esc).join(', ')}</p><p>Área atendida: ${cobreManaus(p.areas)?'toda Manaus':p.areas.map(esc).join(', ')}</p></div><div class="bill">${s[1]===null?'Preço definido após avaliação e orçamento.':`Profissional: ${money(s[1])}<br>Taxa ilustrativa: ${money(total(s[1])-s[1])}<br><strong>Total: ${money(total(s[1]))}</strong>`}</div><button class="primary" data-book="${id}:${index}">${s[1]===null?'Solicitar orçamento':'Solicitar este serviço'}</button><button class="secondary" data-profile="${id}">Conhecer profissional</button>`);}
const originalOrdersView=showOrders;
showOrders=function(){originalOrdersView();const root=$('#modalBody');const allCards=[...root.querySelectorAll('.order')];const list=mode==='prestador'?orders.filter(o=>o.pid===providerId):orders;const tabKey=o=>o.status==='Concluído'?'done':o.status==='Cancelado'?'cancelled':'active';const tabs=document.createElement('div');tabs.className='order-tabs';tabs.innerHTML=[['active','Em andamento'],['done','Concluídos'],['cancelled','Cancelados']].map(([key,label])=>`<button type="button" data-order-tab="${key}" class="${orderTab===key?'active':''}" aria-pressed="${orderTab===key}">${label} (${list.filter(o=>tabKey(o)===key).length})</button>`).join('');root.querySelector('h2').after(tabs);let visible=0;allCards.forEach((card,i)=>{const o=list[i];if(!o)return;card.hidden=tabKey(o)!==orderTab;if(!card.hidden)visible++;let action={'Aguardando orçamento':'Aguardando proposta do profissional.','Solicitado':mode==='prestador'?'Responda à solicitação do cliente.':'Aguardando confirmação do profissional.','Confirmado':mode==='prestador'?'No atendimento, solicite o código de início.':'No atendimento, informe o código para autorizar o início.','Em execução':mode==='prestador'?'Após terminar, solicite o código de conclusão.':'Confira a execução antes de informar o código final.','Concluído':mode==='cliente'&&!reviews.some(r=>r.orderId===o.id)?'Sua avaliação está disponível.':'Atendimento concluído.','Cancelado':'Esta solicitação foi cancelada.'}[o.status];const next=document.createElement('p');next.className='next-action';next.textContent=action;card.prepend(next);});if(!visible&&list.length)root.insertAdjacentHTML('beforeend','<p class="empty">Nenhum pedido nesta aba.</p>');};
const originalMode=setMode;
setMode=function(next){originalMode(next);filterBox.hidden=mode==='prestador';$('#explore').hidden=mode==='prestador';$('#suggestionsButton').hidden=mode==='prestador';$('#ordersButton').classList.toggle('nav-selected',mode==='prestador');orderTab='active';};
const originalDashboard=dashboard;
dashboard=function(){originalDashboard();const root=$('#providerPanel');const oldButtons=['providerOrders','editProvider','addService'].map(id=>$('#'+id));const menu=document.createElement('div');menu.className='provider-menu';oldButtons.forEach(b=>menu.append(b));const catalogButton=document.createElement('button');catalogButton.className='secondary';catalogButton.textContent='Meu catálogo';const reviewButton=document.createElement('button');reviewButton.className='secondary';reviewButton.textContent='Avaliações';menu.append(catalogButton,reviewButton);root.querySelector('.stats').after(menu);const titles=[...root.querySelectorAll('h2')];catalogButton.onclick=()=>titles.find(h=>h.textContent==='Meu catálogo')?.scrollIntoView({behavior:'smooth'});reviewButton.onclick=()=>titles.find(h=>h.textContent==='Avaliações recebidas')?.scrollIntoView({behavior:'smooth'});};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.group){selectedGroup=selectedGroup===b.dataset.group?'':b.dataset.group;category='Todos';sub='';render();}if(b.hasAttribute('data-all-services')){selectedGroup='';category='Todos';sub='';render();}if(b.dataset.offer)openOffer(...b.dataset.offer.split(':').map(Number));if(b.dataset.interest){suggestionForm();const type=document.querySelector('#suggestForm [name="Tipo"]');const box=document.querySelector('#suggestForm [name="text"]');if(type)type.value='Serviço que não encontrei';if(box)box.value='Tenho interesse em: '+b.dataset.interest;}if(b.dataset.orderTab){orderTab=b.dataset.orderTab;showOrders();}if(b.dataset.clearFilter){const id=b.dataset.clearFilter;if(id==='group'){selectedGroup='';category='Todos';sub='';}else if(id==='category'){category='Todos';sub='';}else if(id==='sub')sub='';else $('#'+id).value=id==='rating'?'0':'';render();}});
$('#reset').onclick=()=>{selectedGroup='';category='Todos';sub='';$('#query').value='';$('#district').value='';$('#rating').value='0';$('#modality').value='';$('#nature').value='';$('#sort').value='recommended';render();};
$('#explore').onclick=()=>{setMode('cliente');$('#query').focus();filterBox.scrollIntoView({behavior:'smooth'});};
$('footer span').textContent='Manaus • Protótipo local v0.3';render();
// O seletor original guardava uma referência à renderização anterior.
$('#modality').onchange=()=>render();$('#nature').onchange=()=>render();

