const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const fixture=`
window.testState={user:{id:'provider-1',email:'teste@example.test'},mode:'provider',failMessage:false,expired:false,profileError:false,calls:[],listeners:[]};
const provider={id:'provider-1',display_name:'Oficina Teste',bio:'Reparos',approval_status:'approved'};
const service={id:1,provider_id:'provider-1',category:'Elétrica',subcategory:'Tomadas e interruptores',title:'Troca de tomada',description:'Troca de tomada e avaliação do ponto.',pricing_type:'fixed',starting_price:100,active:true};
const request={id:'request-1',provider_id:'provider-1',client_id:'client-1',district:'Tarumã',description:'Preciso trocar duas tomadas na sala.',preferred_date:'2099-10-05',status:'requested',created_at:'2026-10-05T15:00:00Z'};
const quote={id:'quote-1',request_id:'request-1',provider_id:'provider-1',amount:100,scope:'Troca de duas tomadas na sala',materials:'Materiais pelo cliente',scheduled_date:'2099-10-05',status:'accepted',created_at:'2026-10-05T15:00:00Z',service_requests:{status:'requested'}};
function query(table){const filters=[];let head=false,one=false,start=0,end=499;const q={select(s,o){head=!!o?.head;return q},eq(k,v){filters.push([k,v]);return q},in(){return q},order(){return q},limit(n){end=n-1;return q},range(a,b){start=a;end=b;return q},single(){one=true;return q},maybeSingle(){one=true;return q},update(){return q},insert(){return q},delete(){return q},upsert(){return q},then(resolve,reject){
 window.testState.calls.push({table,filters,start,end});
 let rows=[];switch(table){case 'profiles':if(testState.profileError)return Promise.resolve({data:null,error:{message:'profile unavailable'}}).then(resolve,reject);rows=[{id:testState.user?.id,full_name:'Teste Pessoa',phone:'92999999999',district:'Tarumã',address_line:'Rua teste',address_number:'1',account_type:testState.mode==='provider'?'both':'client',status:'active'}];break;case 'provider_profiles':rows=[provider];break;case 'provider_services':rows=[service];break;case 'provider_service_areas':rows=[{provider_id:'provider-1',district:'Tarumã'}];break;case 'provider_private_details':rows=[{provider_id:'provider-1',document_number:'12345678900',business_name:'Teste Pessoa'}];break;case 'service_requests':rows=[request];break;case 'request_quotes':rows=[quote];break;case 'request_messages':rows=[{id:1,request_id:'request-1',sender_id:'client-1',body:'Olá, preciso de orçamento.',created_at:'2026-10-05T15:00:00Z'}];break;}
 for(const [k,v] of filters)rows=rows.filter(r=>k.includes('.')?true:r[k]===v);
 const count=rows.length;return Promise.resolve({data:head?null:one?(rows[0]||null):rows.slice(start,end+1),count,error:null}).then(resolve,reject);
 }};return q;}
const client={from:query,rpc:async(name,args)=>{testState.calls.push({rpc:name,args});if(name==='admin_is_current_user')return {data:false};if(name==='mp_my_test_connection')return {data:[{mp_user_id:3736210841,token_expires_at:testState.expired?'2000-01-01':'2099-01-01'}]};if(name==='send_request_message' && testState.failMessage)throw new Error('offline');if(name==='prepare_test_payment')return {data:'intent-1'};return {data:'request-1'};},auth:{getSession:async()=>({data:{session:testState.user?{user:testState.user}:null}}),onAuthStateChange(fn){testState.listeners.push(fn);return {data:{subscription:{unsubscribe(){}}}};},signOut:async()=>{testState.user=null;for(const f of testState.listeners)f('SIGNED_OUT',null);return {error:null};}},storage:{from(){return {list:async()=>({data:[]})}}}};
window.supabase={createClient:()=>client};
`;
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='cdn.jsdelivr.net')return route.fulfill({contentType:'text/javascript',body:fixture});if(u.hostname==='local.ajura.test'){const file=path.basename(u.pathname) || 'index.html';if(fs.existsSync(file))return route.fulfill({path:path.resolve(file),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});}return route.abort();});
 await page.goto('https://local.ajura.test/index.html');await page.waitForSelector('#realCards .offer-card');
 assert.equal(await page.locator('#realCatalog').count(),1);assert.equal(await page.locator('#catalog').isVisible(),false);assert.equal(await page.locator('#ordersButton').isVisible(),false);
 await page.click('#accountButton');await page.click('#realProviderButton');await page.waitForSelector('#ajuraAcceptedTotal');await page.waitForFunction(()=>document.querySelector('#ajuraAcceptedTotal')?.textContent.includes('100'));
 assert.equal(await page.locator('#modal').evaluate(el=>el.open),false);assert.equal(await page.locator('#realCatalog').isVisible(),false);
 assert.match(await page.locator('#ajuraProfessionalDashboard').innerText(),/Nenhum recebimento ainda/);
 await page.click('#ajuraEditProfessional');assert(!((await page.locator('#modalBody').innerText()).includes('[object PointerEvent]')));await page.click('#close');
 await page.click('#ajuraAllRequests');await page.waitForSelector('[data-conversation]');assert.equal(await page.inputValue('#requestRole'),'provider');await page.click('[data-conversation]');await page.waitForSelector('#sendRealMessage');
 await page.fill('#sendRealMessage textarea','   ');await page.click('#sendRealMessage button');assert.match(await page.locator('#messageError').innerText(),/Escreva uma mensagem/);
 await page.evaluate(()=>testState.failMessage=true);await page.fill('#sendRealMessage textarea','Teste de falha de rede');await page.click('#sendRealMessage button');await page.waitForFunction(()=>!document.querySelector('#sendRealMessage button').disabled);
 assert.equal(await page.inputValue('#sendRealMessage textarea'),'Teste de falha de rede');assert.match(await page.locator('#messageError').innerText(),/Falha de conexão/);
 await page.click('#close');await page.click('#ajuraModeToggle');await page.waitForSelector('#realCatalog',{state:'visible'});
 await page.selectOption('#realDistrict','Centro');assert.equal(await page.locator('#realCards .offer-card').count(),0);await page.click('#clearRealFilters');assert.equal(await page.locator('#realCards .offer-card').count(),1);
 await page.evaluate(()=>{testState.user={id:'client-1',email:'cliente@example.test'};testState.mode='client';for(const fn of testState.listeners)fn('SIGNED_IN',{user:testState.user});});await page.waitForSelector('[data-request-service]');await page.click('[data-request-service]');await page.waitForSelector('#realRequestForm');assert.match(await page.getAttribute('#realRequestForm input[type=date]','min'),/^\d{4}-\d{2}-\d{2}$/);assert.equal(await page.inputValue('#realRequestForm select'),'Tarumã');await page.click('#close');
 await page.click('#realRequestsButton');await page.waitForSelector('[data-conversation]');await page.click('[data-conversation]');await page.waitForSelector('[data-prepare-payment]');await page.click('[data-prepare-payment]');assert.match(await page.locator('.quote-message').innerText(),/Nenhuma cobrança/);await page.click('#close');
 await page.evaluate(()=>{testState.user={id:'provider-1',email:'teste@example.test'};testState.mode='provider';testState.expired=true;for(const fn of testState.listeners)fn('SIGNED_IN',{user:testState.user});});await page.waitForSelector('#ajuraModeToggle',{state:'visible'});await page.click('#ajuraModeToggle');await page.waitForSelector('#ajuraAcceptedTotal');await page.click('#ajuraEditProfessional');await page.waitForFunction(()=>document.querySelector('#ajuraMpConnection')?.textContent.includes('expirou'));await page.click('#close');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/profissional-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow mobile');
 await page.click('#ajuraModeToggle');await page.screenshot({path:'tests/cliente-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow cliente mobile');
 await page.evaluate(()=>testState.profileError=true);await page.click('#accountButton');await page.waitForSelector('#logoutButton');await page.click('#logoutButton');await page.waitForFunction(()=>testState.user===null);
 assert.deepEqual(errors,[]);console.log('PASS: módulos únicos, fluxos reais, troca de área, ganhos sem dados fictícios, conversa, falha de rede, filtros, perfil, preparação, conexão expirada, celular e saída após erro.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
