const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {parseHTML}=require('linkedom');
function setup(options={}){
 const {document,HTMLElement}=parseHTML('<html><body><header><nav></nav></header><button id="accountButton">Conta</button><dialog id="modal"></dialog></body></html>');
 Object.defineProperty(HTMLElement.prototype,'elements',{configurable:true,get(){return new Proxy({}, {get:(_,key)=>this.querySelector(`[name="${key}"]`)});}});
 document.querySelector('#modal').close=()=>{};
 const calls=[],auth=[],window={};let actor=options.actor===undefined?'client':options.actor;
 const req={id:'request',client_id:'client',provider_id:'provider',district:'Tarumã',status:'requested',description:'Consertar equipamento',preferred_date:'2026-10-10'};
 const context={request:req,tickets:[],messages:[],history:[{id:1,sender_id:'provider',body:'<img src=x onerror=alert(1)>',created_at:'2026-10-06T13:00:00Z'}]};
 const client={auth:{getSession:async()=>({data:{session:actor?{user:{id:actor}}:null}}),onAuthStateChange:fn=>auth.push(fn)},from:()=>({select(){return this},eq(){return this},single:async()=>({data:req})}),rpc:async(name,args)=>{calls.push([name,args]);if(options.fail===name)return {error:{message:'Erro de conexão'}};return {data:name==='support_context'?context:name==='messaging_inbox'?[{id:'request',district:'Tarumã',partner:'Prestador',preview:'Olá',unread:2}]:name==='messaging_unread_count'?2:name==='admin_is_current_user'?Boolean(options.admin):name==='admin_support_queue'?[]:null};}};
 window.AJURA_AUTH={client};window.AJURA_CORE={safe:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),statuses:{requested:'Aberta'},time:()=> '10:00',date:s=>s,counter:()=>{},handleForm:(f,fn,report)=>{f.onsubmit=async e=>{e?.preventDefault();try{await fn()}catch(error){report(error.message)}};}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../messaging.js'),'utf8'),{window,document,setTimeout:()=>{},setInterval:()=>{}});
 return {window,document,calls,auth,context,api:window.AJURA_MESSAGING};
}
test('Painel compacto começa fechado e lista conversas',async()=>{const s=setup();assert.equal(s.document.querySelector('#ajuraChat').hidden,true);await s.api.inbox();assert.equal(s.document.querySelector('#ajuraChat').hidden,false);assert.match(s.document.querySelector('#ajuraChat').textContent,/Prestador/);s.api.close();assert.equal(s.document.querySelector('#ajuraChat').hidden,true);});
test('Histórico seguro e leitura somente dos IDs exibidos',async()=>{const s=setup();await s.api.openRequest('request');const panel=s.document.querySelector('#ajuraChat');assert.equal(panel.querySelector('img'),null);assert.match(panel.textContent,/<img/);assert.ok(panel.querySelector('[data-support-open]'));const receipt=s.calls.find(c=>c[0]==='messaging_mark_read');assert.equal(receipt[1].through_message,1);});
test('Falha ao enviar preserva rascunho; atualizar recupera texto',async()=>{const s=setup({fail:'send_request_message'});await s.api.openRequest('request');let f=s.document.querySelector('[data-chat-compose]');f.elements.body.value='Não perder esta mensagem';await f.onsubmit();assert.equal(f.elements.body.value,'Não perder esta mensagem');await s.api.openRequest('request');f=s.document.querySelector('[data-chat-compose]');assert.equal(f.elements.body.value,'Não perder esta mensagem');});
test('Erro de acesso não mostra histórico; saída encerra o painel',async()=>{const s=setup({fail:'support_context'});await s.api.openRequest('request');assert.match(s.document.querySelector('#ajuraChat').textContent,/Erro de conexão/);s.auth.forEach(fn=>fn('SIGNED_OUT'));assert.equal(s.document.querySelector('#ajuraChat').hidden,true);assert.equal(s.document.querySelector('#ajuraChat').innerHTML,'');});
