const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require('linkedom');
function setup(actor='client',options={}){
 const {document,HTMLElement}=parseHTML('<html><body><main></main></body></html>');Object.defineProperty(HTMLElement.prototype,'elements',{configurable:true,get(){return new Proxy({}, {get:(_,key)=>this.querySelector(`[name="${key}"]`)});}});
 const calls=[],window={confirm:()=>true},context={window,document,Event:document.defaultView.Event};let refreshed=0;
 window.AJURA_AUTH={client:{rpc:async(name,args)=>{calls.push([name,args]);if(options.fail===name)return {error:{message:'Erro de rede'}};return {data:name==='service_review_context'?{can_review:actor==='client'&&options.completed!==false,review:options.review||null}:name==='provider_review_list'?{rows:[{rating:5,comment:'<img src=x>',service_title:'Servico',created_at:'2026-10-06T18:00:00Z'}],total:1}:name==='provider_review_summary'?[{provider_id:'provider',review_count:2,average_rating:4.824}]:'review-id'};}}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../core.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../service-reviews.js'),'utf8'),context);const body=document.querySelector('main');
 return {window,document,body,calls,attach:()=>window.AJURA_REVIEWS.attach({id:'request',client_id:'client',provider_id:'provider'},actor,body,async()=>refreshed++),refreshCount:()=>refreshed};
}
test('Somente cliente com conclusao recebe cinco notas; sem nota nao envia',async()=>{const s=setup();await s.attach();const f=s.body.querySelector('form');assert.equal(f.querySelectorAll('[name="rating"]').length,5);await f.onsubmit({preventDefault(){}});assert.equal(s.calls.length,1);assert.match(s.body.textContent,/Selecione uma nota/);for(const actor of ['provider','third']){const a=setup(actor);await a.attach();assert.equal(a.body.querySelector('form'),null);}const open=setup('client',{completed:false});await open.attach();assert.equal(open.body.querySelector('form'),null);});
test('Nota e comentario vao ao servidor; falha preserva texto',async()=>{const s=setup('client',{fail:'submit_service_review'});await s.attach();const f=s.body.querySelector('form');f.querySelector('[value="4"]').setAttribute('checked','');f.elements.comment.value='Comentario preservado';await f.onsubmit({preventDefault(){}});assert.equal(s.calls[1][1].stars,4);assert.equal(f.elements.comment.value,'Comentario preservado');assert.match(s.body.textContent,/Erro de rede/);assert.equal(s.refreshCount(),0);});
test('Avaliacao existente nao pode ser reeditada e HTML vira texto',async()=>{const s=setup('client',{review:{rating:1,comment:'<script>alert(1)</script>',created_at:'2026-10-06T18:00:00Z'}});await s.attach();assert.equal(s.body.querySelector('script'),null);assert.equal(s.body.querySelector('form'),null);assert.match(s.body.textContent,/<script>/);});
test('Media exibe uma casa sem alterar valor usado nos filtros',async()=>{const s=setup();const stats=await s.window.AJURA_REVIEWS.summary(['provider']);assert.match(s.window.AJURA_REVIEWS.label(stats.get('provider')),/4,8/);assert.equal(stats.get('provider').average_rating,4.824);assert.equal(s.window.AJURA_REVIEWS.label({review_count:0,average_rating:null}),'Novo na plataforma');});
test('Lista publica nao interpreta HTML e erro nao libera formulario',async()=>{const s=setup();await s.window.AJURA_REVIEWS.list('provider',s.body);assert.equal(s.body.querySelector('img'),null);assert.match(s.body.textContent,/<img/);const f=setup('client',{fail:'service_review_context'});await f.attach();assert.equal(f.body.querySelector('form'),null);});

test('Vitrine filtra pela media sem arredondar e ordena pela reputacao',async()=>{
 const {document}=parseHTML('<html><body><main><section id="catalog"></section></main></body></html>');
 const proto=Object.getPrototypeOf(document.createElement('select'));Object.defineProperty(proto,'value',{configurable:true,get(){return this.querySelector('option[selected]')?.getAttribute('value')||this.querySelector('option')?.getAttribute('value')||'';},set(v){this.querySelectorAll('option').forEach(o=>o.getAttribute('value')===String(v)?o.setAttribute('selected',''):o.removeAttribute('selected'));}});
 const profiles=[{id:'a',display_name:'A'},{id:'b',display_name:'B'},{id:'c',display_name:'C'}],services=profiles.map((p,i)=>({id:i+1,provider_id:p.id,category:'Eletrica',subcategory:'Tomada',title:['Primeiro','Segundo','Terceiro'][i],description:'Servico real',pricing_type:'quote'})),areas=profiles.map(p=>({provider_id:p.id,district:'Taruma'}));
 const ratings=new Map([['a',{review_count:10,average_rating:4.79}],['b',{review_count:10,average_rating:4.824}],['c',{review_count:0,average_rating:null}]]);
 const window={AJURA_AUTH:{client:{auth:{getSession:async()=>({data:{session:{user:{id:'client'}}}}),onAuthStateChange:()=>{}},from(table){return {table,select(){return this},eq(){return this},in(){return this},order(){return this}};}}},AJURA_CORE:{safe:s=>String(s??''),money:()=>'',allRows:async f=>({rows:({provider_profiles:profiles,provider_services:services,provider_service_areas:areas})[f().table],truncated:false}),debounce:f=>f},AJURA_REVIEWS:{summary:async()=>ratings,label:r=>r.review_count?Number(r.average_rating).toFixed(1):'Novo na plataforma',list:()=>{}}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../real-catalog.js'),'utf8'),{window,document,normalize:s=>String(s).toLowerCase(),SERVICE_CATALOG:[{category:'Eletrica',subs:['Tomada']}],BAIRROS_MANAUS:['Taruma'],setTimeout});
 await new Promise(setImmediate);await new Promise(setImmediate);
 const rating=document.querySelector('#realRating');assert.equal(rating.disabled,false);rating.value='4.8';rating.onchange({target:rating});assert.equal(document.querySelectorAll('.offer-card').length,1);assert.match(document.querySelector('.offer-card').textContent,/Segundo/);
 rating.value='0';rating.onchange({target:rating});const sort=document.querySelector('#realSort');sort.value='rating';sort.onchange({target:sort});assert.match(document.querySelector('.offer-card').textContent,/Segundo/);assert.match(document.querySelectorAll('.offer-card')[2].textContent,/Novo na plataforma/);
});
