const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {parseHTML}=require('linkedom');
function setup(actor='client',options={}){
 const {document,HTMLElement}=parseHTML('<html><body><main></main></body></html>');
 Object.defineProperty(HTMLElement.prototype,'elements',{configurable:true,get(){return new Proxy({}, {get:(_,key)=>this.querySelector(`[name="${key}"]`)});}});
 const calls=[],window={confirm:()=>true},context={window,document,Event:document.defaultView.Event};let refreshed=0;
 window.AJURA_AUTH={client:{rpc:async(name,args)=>{calls.push([name,args]);if(options.fail===name)return {error:{message:'Erro de rede'}};return {data:name==='service_execution_context'?{status:options.status||'requested',phase:options.phase===undefined?'start':options.phase}:name==='issue_service_code'?{code:'012345',phase:'start',expires_at:'2026-10-06T18:00:00Z'}:{ok:options.ok!==false,status:'in_progress',message:'Codigo incorreto',remaining_attempts:4}};}}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../core.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../service-execution.js'),'utf8'),context);
 const body=document.querySelector('main');return {document,calls,body,attach:()=>window.AJURA_SERVICE_EXECUTION.attach({id:'request',client_id:'client',provider_id:'provider'},actor,body,async()=>{refreshed++}),refreshCount:()=>refreshed};
}
test('Cliente gera codigo somente pelo servidor e recebe aviso sem pagamento',async()=>{const s=setup();await s.attach();assert.equal(s.body.querySelector('[data-confirm-code]'),null);await s.body.querySelector('[data-issue-code]').onclick();assert.match(s.body.querySelector('[data-issued-code]').textContent,/012345/);assert.match(s.body.textContent,/Nao cobram nem liberam/);assert.equal(s.calls[1][0],'issue_service_code');});
test('Prestador nao recebe geracao nem codigo privado; confirmacao atualiza pedido',async()=>{const s=setup('provider');await s.attach();assert.equal(s.body.querySelector('[data-issue-code]'),null);const f=s.body.querySelector('form');f.elements.code.value='012345';await f.onsubmit({preventDefault(){}});assert.equal(s.refreshCount(),1);assert.equal(f.elements.code.value,'');});
test('Codigo incorreto preserva entrada e informa tentativas sem atualizar estado',async()=>{const s=setup('provider',{ok:false});await s.attach();const f=s.body.querySelector('form');f.elements.code.value='111111';await f.onsubmit({preventDefault(){}});assert.equal(s.refreshCount(),0);assert.equal(f.elements.code.value,'111111');assert.match(s.body.textContent,/Tentativas restantes: 4/);});
test('Terceiro nao consulta codigos; pedido concluido nao oferece acao',async()=>{let s=setup('third');await s.attach();assert.equal(s.calls.length,0);s=setup('client',{status:'completed',phase:null});await s.attach();assert.equal(s.body.querySelector('[data-issue-code]'),null);assert.equal(s.body.querySelector('form'),null);});
test('Falha de geracao nao exibe codigo e libera botao',async()=>{const s=setup('client',{fail:'issue_service_code'});await s.attach();const b=s.body.querySelector('[data-issue-code]');await b.onclick();assert.equal(s.body.querySelector('[data-issued-code]').textContent,'');assert.equal(b.disabled,false);assert.match(s.body.textContent,/Erro de rede/);});
