const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{parseHTML}=require('linkedom');
function setup(o={}){
 const {document,HTMLElement}=parseHTML('<html><body><header><nav></nav></header><button id="accountButton"></button><dialog id="modal"><div id="modalBody"></div></dialog><main></main></body></html>');Object.defineProperty(HTMLElement.prototype,'elements',{configurable:true,get(){return new Proxy({}, {get:(_,k)=>this.querySelector(`[name="${k}"]`)});}});Object.defineProperty(Object.getPrototypeOf(document.createElement('select')),'value',{configurable:true,get(){return this.querySelector('option[selected]')?.getAttribute('value')||this.querySelector('option')?.getAttribute('value')||'';},set(v){this.querySelectorAll('option').forEach(x=>x.getAttribute('value')===v?x.setAttribute('selected',''):x.removeAttribute('selected'));}});
 let refreshed=0;const calls=[],opened=[],profile={full_name:'Cliente',phone:'92999999999',district:'Taruma',account_type:'client',status:'active',address_line:'Rua cadastrada',address_number:'12',address_complement:'Apto 3',address_reference:'Portao'};
 const client={auth:{getSession:async()=>({data:{session:{user:{id:o.actor||'client'}}}}),onAuthStateChange(){}},from(table){return {select(){return this},eq(){return this},single:async()=>({data:table==='provider_services'?{id:1,provider_id:'provider',title:'Servico'}:profile}),order:async()=>({data:[{district:'Taruma'}]})};},rpc:async(n,a)=>{calls.push([n,a]);if(o.fail===n)return {error:{message:'Resposta indisponivel'}};return {data:n==='request_location_context'?{confirmed:o.confirmed!==false,can_confirm:Boolean(o.can_confirm),quote_accepted:Boolean(o.accepted),service_mode:o.mode||'on_site',district:'Taruma',address:o.address||null,confirmed_at:'2026-10-06'}:'request-id'};}};
 const window={confirm:()=>true,crypto:{randomUUID:()=> '00000000-0000-0000-0000-000000000011'},AJURA_AUTH:{client},AJURA_MESSAGING:{openRequest:async id=>opened.push(id)}};const ctx={window,document,Event:document.defaultView.Event,modal:h=>document.querySelector('#modalBody').innerHTML=h,toast:m=>window.lastToast=m,setTimeout};vm.createContext(ctx);for(const f of ['core.js','service-location.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),ctx);
 return {window,document,calls,opened,profile,body:document.querySelector('main'),refreshCount:()=>refreshed,attach:()=>window.AJURA_LOCATION.attach({id:'request',client_id:'client',provider_id:'provider',status:'requested'},o.actor||'client',document.querySelector('main'),async()=>refreshed++),loadRequests:()=>vm.runInContext(fs.readFileSync(path.join(__dirname,'../requests.js'),'utf8'),ctx)};
}
test('Prestador sem autorizacao nao recebe endereco ou formulario',async()=>{const s=setup({actor:'provider'});await s.attach();assert.match(s.body.textContent,/protegido/);assert.equal(s.body.querySelector('form'),null);assert.doesNotMatch(s.body.textContent,/Rua cadastrada/);});
test('Endereco autorizado e escapado e vem do snapshot',async()=>{const s=setup({actor:'provider',address:{line:'<img src=x>',number:'22',complement:'<script>x</script>'}});await s.attach();assert.equal(s.body.querySelector('img'),null);assert.equal(s.body.querySelector('script'),null);assert.match(s.body.textContent,/<img/);assert.doesNotMatch(s.body.textContent,/Rua cadastrada/);});
test('Remoto nao mostra endereco e envia campos fisicos nulos',async()=>{const s=setup({mode:'remote'});await s.attach();assert.match(s.body.textContent,/remoto \/ online/);s.body.innerHTML=`<form>${s.window.AJURA_LOCATION.markup(s.profile)}</form>`;const f=s.body.querySelector('form');s.window.AJURA_LOCATION.bind(f);f.elements.service_mode.value='remote';f.elements.service_mode.onchange();assert.equal(f.querySelector('[data-location-fields]').hidden,true);assert.equal(f.elements.location_line.disabled,true);f.elements.location_confirmed.checked=true;assert.equal(s.window.AJURA_LOCATION.read(f).location_line,null);});
test('Legado exige confirmacao explicita com alerta de proposta aceita',async()=>{const s=setup({confirmed:false,can_confirm:true,accepted:true});await s.attach();const f=s.body.querySelector('form');assert.match(f.textContent,/proposta ja foi aceita/);assert.equal(f.elements.location_confirmed.checked,false);await f.onsubmit({preventDefault(){}});assert.equal(s.calls.length,1);assert.match(f.textContent,/Confirme o local/);});
test('Falha na confirmacao preserva o endereco digitado',async()=>{const s=setup({confirmed:false,can_confirm:true,fail:'confirm_request_location'});await s.attach();const f=s.body.querySelector('form');f.elements.location_line.value='Outro local informado';f.elements.location_confirmed.checked=true;await f.onsubmit({preventDefault(){}});assert.equal(s.calls[1][1].location_line,'Outro local informado');assert.equal(f.elements.location_line.value,'Outro local informado');assert.equal(s.refreshCount(),0);assert.match(f.textContent,/Resposta indisponivel/);});
test('Erro de consulta nao inventa local nem libera formulario',async()=>{const s=setup({fail:'request_location_context',can_confirm:true});await s.attach();assert.equal(s.body.querySelector('form'),null);assert.match(s.body.textContent,/Local indisponivel/);});
test('Nova solicitacao usa RPC protegido e mantem a chave na repeticao',async()=>{const s=setup({fail:'create_service_request_with_location'});s.loadRequests();await s.window.AJURA_REQUESTS.create(1);const f=s.document.querySelector('#realRequestForm');assert.ok(f);f.elements.description.value='Descricao de servico suficiente';f.elements.date.value='2026-10-10';f.elements.location_confirmed.checked=true;await f.onsubmit({preventDefault(){}});await f.onsubmit({preventDefault(){}});const sends=s.calls.filter(([n])=>n==='create_service_request_with_location');assert.equal(sends.length,2);assert.equal(sends[0][1].submission_key,sends[1][1].submission_key);assert.equal(sends[0][1].location_line,'Rua cadastrada');assert.equal(s.opened.length,0);});
test('Solicitacao nao e enviada sem confirmacao do local',async()=>{const s=setup();s.loadRequests();await s.window.AJURA_REQUESTS.create(1);const f=s.document.querySelector('#realRequestForm');f.elements.description.value='Servico com descricao suficiente';await f.onsubmit({preventDefault(){}});assert.equal(s.calls.length,0);assert.match(f.textContent,/Confirme o local/);});
