const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{parseHTML}=require('linkedom');
function setup(o={}){const {document,HTMLElement}=parseHTML('<html><body><main></main></body></html>');Object.defineProperty(HTMLElement.prototype,'elements',{configurable:true,get(){return new Proxy({}, {get:(_,k)=>this.querySelector(`[name="${k}"]`)});}});Object.defineProperty(Object.getPrototypeOf(document.createElement('select')),'value',{configurable:true,get(){return this.querySelector('option[selected]')?.getAttribute('value')||this.querySelector('option')?.getAttribute('value')||'';}});let refreshed=0;const calls=[],window={confirm:()=>true,AJURA_AUTH:{client:{rpc:async(n,a)=>{calls.push([n,a]);if(n===o.fail)return {error:{message:'Pedido mudou. Atualize a conversa'}};if(n==='service_cancellation_context'&&o.wait)return o.wait;return {data:n==='service_cancellation_context'?{rows:o.rows||[],total:(o.rows||[]).length,request_status:o.status||'in_progress',can_request:o.can_request!==false,can_decide:Boolean(o.can_decide),pending_id:o.pending||null}:'cancel-id'};}}}};const ctx={window,document,Event:document.defaultView.Event};vm.createContext(ctx);for(const f of ['core.js','service-cancellation.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),ctx);const body=document.querySelector('main');return {window,document,body,calls,refreshCount:()=>refreshed,attach:()=>window.AJURA_SERVICE_CANCELLATION.attach({id:'request',client_id:'client',provider_id:'provider'},o.actor||'client',body,async()=>refreshed++,Boolean(o.central))};}
test('Participante solicita analise; motivo curto nao envia',async()=>{const s=setup();await s.attach();const f=s.body.querySelector('[data-cancel-request]');assert.ok(f);f.elements.reason.value='curto';await f.onsubmit({preventDefault(){}});assert.equal(s.calls.length,1);assert.match(s.body.textContent,/10 a 1000/);assert.match(s.body.textContent,/nao pausa nem cancela automaticamente/);});
test('Falha preserva motivo; sucesso atualiza sem fabricar estado cancelado',async()=>{for(const fail of [true,false]){const s=setup({fail:fail?'request_service_cancellation':null});await s.attach();const f=s.body.querySelector('form');f.elements.reason.value='Servico nao corresponde ao combinado';await f.onsubmit({preventDefault(){}});assert.equal(s.calls[1][1].target_request,'request');if(fail){assert.equal(f.elements.reason.value,'Servico nao corresponde ao combinado');assert.match(f.textContent,/Pedido mudou/);assert.equal(s.refreshCount(),0);}else assert.equal(s.refreshCount(),1);assert.equal(s.calls.some(([n])=>n==='confirm_service_code'),false);}});
test('Pedido encerrado e sem historico nao recebe formulario; terceiro nao solicita',async()=>{const closed=setup({status:'completed',can_request:false});await closed.attach();assert.equal(closed.body.querySelector('section'),null);const third=setup({actor:'third'});await third.attach();assert.equal(third.body.querySelector('form'),null);});
test('Solicitacao pendente impede duplicata e historico trata HTML como texto',async()=>{const s=setup({pending:'cancel-id',can_request:false,rows:[{requested_by:'provider',reason:'<img src=x>',status:'pending',created_at:'2026-10-06'}]});await s.attach();assert.equal(s.body.querySelector('form'),null);assert.equal(s.body.querySelector('img'),null);assert.match(s.body.textContent,/<img/);assert.match(s.body.textContent,/aguardando analise/);});
test('Decisao disponivel somente na Central; erro preserva justificativa',async()=>{const normal=setup({can_decide:true,pending:'cancel-id',can_request:false,rows:[{status:'pending'}]});await normal.attach();assert.equal(normal.body.querySelector('[data-cancel-decision]'),null);const s=setup({central:true,can_decide:true,can_request:false,pending:'cancel-id',rows:[{status:'pending'}],fail:'admin_decide_service_cancellation'});await s.attach();const f=s.body.querySelector('[data-cancel-decision]');f.elements.resolution.value='Manter execucao apos ouvir os dois lados';await f.onsubmit({preventDefault(){}});assert.equal(s.calls[1][1].target_cancellation,'cancel-id');assert.equal(s.calls[1][1].decision,'continue');assert.match(f.textContent,/Pedido mudou/);assert.equal(f.elements.resolution.value,'Manter execucao apos ouvir os dois lados');});
test('Consulta falha nao libera acoes de cancelamento',async()=>{const s=setup({fail:'service_cancellation_context'});await s.attach();assert.equal(s.body.querySelector('form'),null);assert.ok(s.body.querySelector('[data-retry]'));});
test('Resposta tardia nao repoe conteudo ao fechar conversa',async()=>{let resolve;const s=setup({wait:new Promise(r=>resolve=r)});const task=s.attach();s.body.replaceChildren();resolve({data:{rows:[{reason:'conteudo privado'}],total:1,can_request:true}});await task;assert.equal(s.body.textContent,'');});

function setupMessaging(options={}){
 const {document,HTMLElement}=parseHTML('<html><body><header><nav></nav></header><button id="accountButton">Conta</button><dialog id="modal"></dialog></body></html>');
 Object.defineProperty(HTMLElement.prototype,'elements',{configurable:true,get(){return new Proxy({}, {get:(_,key)=>this.querySelector(`[name="${key}"]`)});}});
 document.querySelector('#modal').close=()=>{};
 const calls=[],auth=[],window={};let actor=options.actor===undefined?'client':options.actor;
 const req={id:'request',client_id:'client',provider_id:'provider',district:'Tarumã',status:'requested',description:'Consertar equipamento',preferred_date:'2026-10-10'};
 const context={request:req,tickets:[],messages:[],history:[{id:1,sender_id:'provider',body:'<img src=x onerror=alert(1)>',created_at:'2026-10-06T13:00:00Z'}]};
 const client={auth:{getSession:async()=>({data:{session:actor?{user:{id:actor}}:null}}),onAuthStateChange:fn=>auth.push(fn)},from:()=>({select(){return this},eq(){return this},single:async()=>({data:req})}),rpc:async(name,args)=>{calls.push([name,args]);if(options.fail===name)return {error:{message:'Erro de conexão'}};return {data:name==='support_context'?context:name==='messaging_inbox'?[{id:'request',district:'Tarumã',partner:'Prestador',preview:'Olá',unread:2}]:name==='messaging_unread_count'?2:name==='admin_is_current_user'?Boolean(options.admin):name==='admin_support_queue'?[]:null};}};
 window.AJURA_AUTH={client};window.AJURA_CORE={safe:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),statuses:{requested:'Aberta'},time:()=> '10:00',date:s=>s,counter:()=>{},handleForm:(f,fn,report)=>{f.onsubmit=async e=>{e?.preventDefault();try{await fn()}catch(error){report(error.message)}};}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../messaging.js'),'utf8'),{window,document,setTimeout:()=>{},setInterval:()=>{}});
 return {window,document,calls,auth,context,api:window.AJURA_MESSAGING};
}

test('Conversa normal e Central integram o modulo com modos separados',async()=>{for(const central of [false,true]){const s=setupMessaging({admin:central});let captured;s.window.AJURA_SERVICE_CANCELLATION={attach:async(...args)=>captured=args};await s.api.openRequest('request',central);assert.equal(captured[4],central);assert.equal(captured[0].id,'request');}});
test('Encerrar atendimento com pendencia mostra erro do servidor e preserva resolucao',async()=>{const s=setupMessaging({admin:true,fail:'resolve_support_ticket'});s.context.tickets=[{id:'ticket',status:'open'}];await s.api.openRequest('request',true);const f=s.document.querySelector('[data-support-resolve]');f.elements.resolution.value='Resolucao a preservar em caso de erro';await f.onsubmit();assert.equal(f.elements.resolution.value,'Resolucao a preservar em caso de erro');assert.match(f.textContent,/Erro de conexão/);});
